version: "3.8"

services:
  app:
    build: .
    container_name: bun_app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: capstone
      PORT: 5000
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "bunx nodemon src/app.js"
    restart: always

  redis:
    image: redis:7
    container_name: bun_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  postgres:
    image: postgres:15
    container_name: bun_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: capstone
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  redis_data:
  pgdata:
